### ISSUE TITLE
Exception while processing data

### ISSUE THREAD

**Issue by borice** [gnames/htindex#9]
Got the following error in the console. I cannot yet tell whether the `htindex` process on  the cluster node that generated this error is still running or not.  Is this an ignorable error, or a bug?

```
panic: runtime error: index out of range [770223] with length 770223

goroutine 71 [running]:
github.com/gnames/gnfinder/token.lastWordForLine(0xc28e8ae000, 0xbc0af, 0xbc800, 0xbc0ae, 0xc0c5926650)
	/home/dimus/go/pkg/mod/github.com/gnames/gnfinder@v0.8.8/token/tokenize.go:54 +0xa0
github.com/gnames/gnfinder/token.lineEndsWithDash(0xc28e8ae000, 0xbc0af, 0xbc800, 0xbc0ae, 0xc28eb9e2ac, 0x3, 0x755, 0xc0c5926648, 0x5, 0xbc0ab, ...)
	/home/dimus/go/pkg/mod/github.com/gnames/gnfinder@v0.8.8/token/tokenize.go:46 +0x90
github.com/gnames/gnfinder/token.Tokenize(0xc28e8ae000, 0xbc0af, 0xbc800, 0xc28e8ae000, 0xbc0af, 0xbc800)
	/home/dimus/go/pkg/mod/github.com/gnames/gnfinder@v0.8.8/token/tokenize.go:26 +0x433
github.com/gnames/gnfinder.(*GNfinder).FindNames(0xc009a74000, 0xc265516000, 0x129bab, 0x172000, 0x129bab)
	/home/dimus/go/pkg/mod/github.com/gnames/gnfinder@v0.8.8/find.go:21 +0xb9
github.com/gnames/htindex.(*HTindex).worker(0xc00013a050, 0xc000102120, 0xc0001021e0, 0xc000102180, 0xc0075f27c0)
	/home/dimus/go/src/github.com/gnames/htindex/worker.go:81 +0x410
created by github.com/gnames/htindex.(*HTindex).Run
	/home/dimus/go/src/github.com/gnames/htindex/runner.go:23 +0x24e
```

**Comment by borice** [comment]
Any ideas?  I'm stuck at this point as it seems the jobs die when this error occurs.

**Comment by dimus** [comment]
Definitely a bug, hopefully we will find a way to reproduce it, as it is not a common one.

**Comment by dimus** [comment]
Related to https://github.com/gnames/gnfinder/issues/30
